### ISSUE TITLE
Compiled dist/ file does not work in node

### ISSUE THREAD

**Issue by StuAtGit** [bettiolo/oauth-signature-js#15]
The compiled version:
    dist/oauth-signature.js

Does not work in node, because it uses the window object, before any checks for the window object:

```
/*! url - v1.8.6 - 2013-11-22 */window.url=functi ....
;(function() {
	'use strict';

	// In node there is no global Window object
	var isNode = (typeof window === 'undefined');
```

**Comment by StuAtGit** [comment]
Nm. I didn't know what I was doing. Used bower for a bit, but just learning the npm packaging system.

**Comment by bettiolo** [comment]
Thank you, have you got any suggestions on how to improve the docs to make this easier to understand?

**Comment by StuAtGit** [comment]
I included the wrong header file. I guess an example like:

```
    <script language="javascript" type="text/javascript" src="bower_components/oauth-signature/dist/oauth-signature.js"></script>
```
Would have cleared it up for me. Thanks!

**Comment by bettiolo** [comment]
thank you!
