### ISSUE TITLE
Cannot get Twitter Usertimeline with oauth-signature-js + $http request

### ISSUE THREAD

**Issue by joDelicious** [bettiolo/oauth-signature-js#25]
Hello !

I've been spending days to make it work, without success...

Here is the question on Stackoverflow:
http://stackoverflow.com/questions/36961045/simple-method-to-retrieve-twitter-user-timeline

& a plunker :
https://plnkr.co/edit/kF9iqCOv31ZXuuy4vlSp?p=info

Thank you....

Johan

**Comment by bettiolo** [comment]
I will check to see if I can provide you a working example. Keep in mind that putting the client_secret in the browser may be a bed idea.

**Comment by joDelicious** [comment]
OK thank you Bettelio, 
i understand now i should avoid using the browser for security reasons. 

I am using Angular on top of a Wordpress/Apache server. Does this mean that i should keep using php/curl in this case for http request, so not use Angular for this task ?

Cheerz!
Johan

**Comment by framp** [comment]
Bettelio a vapore:
I'd love to see more examples as well!

**Comment by bettiolo** [comment]
@joDelicious it might be better to get your angular app to talk to Apache and do the calls to twitter from Apache

**Comment by joDelicious** [comment]
@bettiolo    Arg :)    Do you have any advise on tools/paths/keywords to dig ?   Thank you.

**Comment by bettiolo** [comment]
Not really, sorry

**Comment by joDelicious** [comment]
@bettiolo I have answered my own question.  Thanx for the input. 
[http://stackoverflow.com/questions/36961045/simple-method-to-retrieve-twitter-user-timeline-with-http#answer-37199813](http://stackoverflow.com/questions/36961045/simple-method-to-retrieve-twitter-user-timeline-with-http#answer-37199813)
