### ISSUE TITLE
update `uri-js` to 3.x.x, 2.1.1 is vulnerable to `Regular Expression Denial Of Service`

### ISSUE THREAD

**Issue by despairblue** [bettiolo/oauth-signature-js#36]
See https://nodesecurity.io/advisories/100

**Comment by SPAHI4** [comment]
also, it should fix an error with react-native

**Comment by aniltallam** [comment]
@bettiolo can you merge the above PR and release new npm version?

**Comment by bettiolo** [comment]
I will, but I think that the PR did not update the client side uri-js

**Comment by bettiolo** [comment]
Merged and released as 1.5.0
