### ISSUE TITLE
SOS,when i am exchange token, the signature is wrong

### ISSUE THREAD

**Issue by shadowprompt** [bettiolo/oauth-signature-js#37]
![2017-07-15_000851](https://user-images.githubusercontent.com/1947096/28220461-1a10a172-68f2-11e7-832b-8dc9c5618ded.png)

but when i am in the fisrt step for request token, it works well, the signature is right, the param 'tokenSecret' is empty, just when i put in the  param 'tokenSecret' in the next step, the signature is wrong.

why? help me, the cryto function works bad when the the  param 'tokenSecret' is set ？

Thx

----I have already solved it .-----

**Comment by bettiolo** [comment]
@shadowprompt how did you solve it?
